### PR TITLE
Fix steps

### LINKED ISSUE #244: Segmentation fault when executing busted with to test files bot importing 'luv'
See this: https://gist.github.com/AitorATuin/46bafaeeb51388c6c1d367083b83c4c6

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6637a92 in uv_walk () from /home/eof/.luarocks/lib/lua/5.1/luv.so
(gdb) bt
#0  0x00007ffff6637a92 in uv_walk () from /home/eof/.luarocks/lib/lua/5.1/luv.so
#1  0x00007ffff663394a in loop_gc () from /home/eof/.luarocks/lib/lua/5.1/luv.so
#2  0x0000000000408058 in ?? ()
#3  0x0000000000408454 in ?? ()
#4  0x000000000040942b in ?? ()
#5  0x000000000040a2b8 in ?? ()
#6  0x00000000004077bb in ?? ()
#7  0x000000000040ddd2 in lua_close ()
#8  0x0000000000403cda in main ()
```

### PR DESCRIPTION
**Pull request by zhaozg**
* fix warning about unused static function
* fix ARM64 (aarch64) Lua "bad light userdata pointer"  …

### CODE REVIEW

**Comment by zhaozg** [comment]
Split from https://github.com/luvit/luv/pull/331, to reduce complexity

File: src/luv.c [hunk 1]
```diff
@@ -18,7 +18,13 @@
 #if (LUA_VERSION_NUM != 503)
 #include "c-api/compat-5.3.h"
 #endif
+#define LUV_SOURCE
 #include "luv.h"
+
+#if defined(__aarch64__)
+#define lua_pushlightuserdata(L, P)  lua_pushinteger((L), (lua_Integer)(P))
```
Comment (squeek502) [inline src/luv.c]: Is this a complete enough fix? `lua_islightuserdata` will not work, for example. Maybe we should just avoid using light userdata instead?

The only places its used right now are:
- https://github.com/luvit/luv/blob/9e6e4f2f98647005d5dc0154ca9161540e73f499/src/thread.c#L118-L129
- https://github.com/luvit/luv/blob/9e6e4f2f98647005d5dc0154ca9161540e73f499/src/work.c#L174-L177
- https://github.com/luvit/luv/blob/9e6e4f2f98647005d5dc0154ca9161540e73f499/src/work.c#L260-L263

Comment (zhaozg) [reply src/luv.c]: I think that's enough, because  we use use lua_pushlightuserdata just as a key for registry table, and not use it as a real pointer or userdata,  lua_pushlightuserdata is keep in luv private source code. As for lua_islightuserdata, we never use it.
The best solution is to remove lightuserdata api from luv, but that large change,  so I use define to get same result.

Comment (zhaozg) [reply src/luv.c]: wait here https://github.com/luvit/luv/blob/9e6e4f2f98647005d5dc0154ca9161540e73f499/src/thread.c#L72-L74 maybe wrong.

**Comment by zhaozg** [comment]
I have removed all lightuserdate from luv.  @squeek502

**Comment by squeek502** [comment]
Is there a reason we aren't using `luaL_ref`/`luaL_unref` for this?

From https://www.lua.org/pil/27.3.2.html:

> You should never use numbers as keys in the registry, because such keys are reserved for the reference system. This system is composed by a couple of functions in the auxiliary library that allow you to store values in the registry without worrying about how to create unique names. (Actually, those functions can act on any table, but they are typically used with the registry.)

**Comment by squeek502** [comment]
@rphillips how would a major version bump work for the versioning luv uses (i.e. right now it basically just mirrors the version of the libuv it binds)?
