### PR TITLE
fix #564, invalid thread argument causes crash.

### LINKED ISSUE #564: Crash when passing a lua object as thread argument
The main thread will crash if I pass a table, etc. as an argument to the thread, as shown below.

```
LuaJIT 2.1.0-beta3 -- Copyright (C) 2005-2021 Mike Pall. https://luajit.org/
JIT: ON SSE3 SSE4.1 BMI2 fold cse dce fwd dse narrow loop abc sink fuse
> uv=require'luv'
> t=uv.new_thread(function(tbl) print(tbl) end, {})
Error: thread arg not support type 'table' at 2> Error: thread arg not support type table at 1Uncaught Error: attempt to call a nil value
```

This problem can be fixed with the following patch.

```diff
diff --git a/src/thread.c b/src/thread.c
index b130593..50ed7e2 100644
--- a/src/thread.c
+++ b/src/thread.c
@@ -201,6 +201,7 @@ static int luv_thread_arg_push(lua_State* L, luv_thread_arg
_t* args, int flags)
     default:
       fprintf(stderr, "Error: thread arg not support type %s at %d",
         lua_typename(L, arg->type), i + 1);
+      lua_pushnil(L);
     }
     i++;
   };
```

However, I think it would be better to change the following part to `return lua_error(L)`. If we call `lua_error` with `luv_thread_arg_set`, will there be a memory leak or some other problem? I have not created a PR because I do not know which modification is preferable for us.
 
https://github.com/luvit/luv/blob/b2572ecf988185b9763965c590f6edbb2bc9b6c3/src/thread.c#L105-L110

### PR DESCRIPTION
**Pull request by erw7**
This is an attempt to fix #564 with a different approach than #565.

Change `luv_work_cb()` to run in protected mode and throw an error in `luv_thread_arg_set()` if an argument of an impermissible type is passed. It's a little more complicated, but I've integrated it into `neovim` and it seems to be working.

### CODE REVIEW

**Review by zhaozg — APPROVED** [review]

**Comment by zhaozg** [comment]
Would you like to add some test about this?

**Comment by erw7** [comment]
> Would you like to add some test about this?

Yes, I would like to add a test. If I link to neovim, it looks like the problem has been solved. However, luajit still crash SIGABRT (core dumped). I'll give it some more consideration.

File: src/work.c [hunk 1]
```diff
@@ -104,14 +107,30 @@ static void luv_work_cb(uv_work_t* req) {
...
+  luv_work_ctx_t* ctx = work->ctx;
+  lua_State *L = work->args.L;
+  luv_ctx_t* lctx = luv_context(L);
+
+  // If exit is called on a thread in the thread pool, abort is called in
+  // uv__threadpool_cleanup, so exit is not called in luv_cfpcall.
+  int i = lctx->thrd_cpcall(L, luv_work_cb, (void*)req, LUVF_CALLBACK_NOEXIT);
+  if (i != LUA_OK) {
+    luv_thread_arg_clear(L, &work->rets, LUVF_THREAD_MODE_ASYNC|LUVF_THREAD_SIDE_CHILD);
+    luv_thread_arg_clear(L, &work->args, LUVF_THREAD_SIDE_CHILD);
```
Comment (zhaozg) [inline src/work.c:132]: Add   ` free(work);` here should fix https://github.com/luvit/luv/pull/566/checks?check_run_id=3639647046#step:5:600

File: src/work.c [hunk 2]
```diff
@@ -104,14 +107,30 @@ static void luv_work_cb(uv_work_t* req) {
...
+  luv_work_t* work =  (luv_work_t*)req->data;
+  luv_work_ctx_t* ctx = work->ctx;
+  lua_State *L = work->args.L;
+  luv_ctx_t* lctx = luv_context(L);
+
+  // If exit is called on a thread in the thread pool, abort is called in
+  // uv__threadpool_cleanup, so exit is not called in luv_cfpcall.
+  int i = lctx->thrd_cpcall(L, luv_work_cb, (void*)req, LUVF_CALLBACK_NOEXIT);
+  if (i != LUA_OK) {
+    luv_thread_arg_clear(L, &work->rets, LUVF_THREAD_MODE_ASYNC|LUVF_THREAD_SIDE_CHILD);
```
Comment (zhaozg) [inline src/work.c:131]: Lua vm must be push back to vm pools cache in main threads.
Should copy and refact code from 
https://github.com/luvit/luv/blob/b2572ecf988185b9763965c590f6edbb2bc9b6c3/src/work.c#L129-L138

Run here means not call luv_after_work_cb

**Review by zhaozg — CHANGES_REQUESTED** [review]

File: src/work.c [hunk 3]
```diff
@@ -104,14 +107,30 @@ static void luv_work_cb(uv_work_t* req) {
...
+static void luv_work_cb_wrapper(uv_work_t* req) {
+  luv_work_t* work =  (luv_work_t*)req->data;
+  luv_work_ctx_t* ctx = work->ctx;
+  lua_State *L = work->args.L;
+  luv_ctx_t* lctx = luv_context(L);
+
+  // If exit is called on a thread in the thread pool, abort is called in
+  // uv__threadpool_cleanup, so exit is not called in luv_cfpcall.
+  int i = lctx->thrd_cpcall(L, luv_work_cb, (void*)req, LUVF_CALLBACK_NOEXIT);
+  if (i != LUA_OK) {
```
Comment (zhaozg) [inline src/work.c:130]: Lua vm must be push back to vm pools cache in main threads to fix https://github.com/luvit/luv/pull/566/checks?check_run_id=3639646912#step:4:9914

Maybe we can copy and refact code from 
https://github.com/luvit/luv/blob/b2572ecf988185b9763965c590f6edbb2bc9b6c3/src/work.c#L129-L138

Run here means not call luv_after_work_cb

**Review by zhaozg — CHANGES_REQUESTED** [review]

File: src/work.c (hunk 3 above)
Comment (zhaozg) [reply src/work.c:130]: Or do a wrapper for luv_work_cb, insure luv_after_work_cb called everytime is a good idea.

File: src/work.c (hunk 1 above)
Comment (zhaozg) [reply src/work.c:132]: Or do a wrapper for luv_work_cb, insure luv_after_work_cb called everytime is a good idea.

File: src/work.c [hunk 4]
```diff
@@ -202,11 +224,17 @@ static int luv_queue_work(lua_State* L) {
     work->args.L = acquire_vm_cb();
   lua_pop(L, 1);
 
-  luv_thread_arg_set(L, &work->args, 2, top, LUVF_THREAD_SIDE_MAIN); //clear in sub threads,luv_work_cb
+  ret = luv_thread_arg_set(L, &work->args, 2, top, LUVF_THREAD_SIDE_MAIN); //clear in sub threads,luv_work_cb
+  if (ret < 0) {
+    luv_thread_arg_clear(L, &work->args, LUVF_THREAD_SIDE_MAIN);
```
Comment (zhaozg) [inline src/work.c:229]: https://github.com/luvit/luv/blob/b2572ecf988185b9763965c590f6edbb2bc9b6c3/src/work.c#L129-L134

Comment (zhaozg) [reply src/work.c:229]: This should help

Comment (erw7) [reply src/work.c:237]: @zhaozg  thanks.

**Comment by zhaozg** [comment]
@erw7 Thank you very much.
