### PR TITLE
fix segfault in luv_check_handle/luv_check_stream

### LINKED ISSUE #633: segfault on luv_check_handle
I've been playing a bit with `luv.handle_get_type`/`luv.fileno` and I noticed that on Lua 5.1/LuaJIT it segfaults with
```lua
luv.handle_get_type(newproxy())
-- or
luv.fileno(newproxy())
```

I traced this back a bit to find it happens in `luv_check_handle`, more specifically on 
```c
if (!handle->data) { goto fail; }
```

I assume this only really happens when passing an empty userdata like with `newproxy`? Why exactly it happens or how it could be possibly fixed is beyond me though, I speculated that this is trying to index the userdata memory block out of bounds but not entirely sure if that is how userdata works.

### PR DESCRIPTION
**Pull request by Bilal2453**
Fixes #633.

Is the style I used here OK? It felt kind of different than the rest of the code, the assignments in the if statements more specifically..

### CODE REVIEW

File: src/handle.c [hunk 1]
```diff
@@ -45,11 +45,17 @@ static uv_handle_t* luv_check_handle(lua_State* L, int index) {
...
+  isHandle = lua_getmetatable(L, index < 0 ? index - 1 : index);
+  if (!isHandle) goto fail;
   lua_rawget(L, -2);
   isHandle = lua_toboolean(L, -1);
   lua_pop(L, 2);
-  if (isHandle) { return handle; }
+  if (!isHandle) goto fail;
+  // cast the uesrdata to uv_handle_t
+  handle = *(uv_handle_t**)udata;
+  if (!handle || !handle->data) goto fail;
```
Comment (squeek502) [inline src/handle.c:56]: Nitpick: I believe this `!handle` check is redundant, as the `*(uv_handle_t**)udata` cast cannot make `handle` null and we already know `udata` is not null.

```suggestion
  if (!handle->data) goto fail;
```

File: src/handle.c [hunk 2]
```diff
@@ -45,11 +45,17 @@ static uv_handle_t* luv_check_handle(lua_State* L, int index) {
...
   lua_getfield(L, LUA_REGISTRYINDEX, "uv_handle");
-  lua_getmetatable(L, index < 0 ? index - 1 : index);
+  isHandle = lua_getmetatable(L, index < 0 ? index - 1 : index);
+  if (!isHandle) goto fail;
   lua_rawget(L, -2);
   isHandle = lua_toboolean(L, -1);
   lua_pop(L, 2);
-  if (isHandle) { return handle; }
+  if (!isHandle) goto fail;
+  // cast the uesrdata to uv_handle_t
```
Comment (squeek502) [inline src/handle.c:54]:
```suggestion
  // cast the userdata to uv_handle_t
```

**Review by squeek502 — COMMENTED** [review]
Some minor nitpicks, but overall looks good.

File: src/stream.c [hunk 3]
```diff
@@ -33,11 +33,17 @@ static uv_stream_t* luv_check_stream(lua_State* L, int index) {
...
+  isStream = lua_getmetatable(L, index < 0 ? index - 1 : index);
+  if (!isStream) goto fail;
   lua_rawget(L, -2);
   isStream = lua_toboolean(L, -1);
   lua_pop(L, 2);
-  if (isStream) { return handle; }
+  if (!isStream) goto fail;
+  // cast the userdata to uv_stream_t
+  handle = *(uv_stream_t**)udata;
+  if (!handle || !handle->data) goto fail;
```
Comment (squeek502) [inline src/stream.c:44]:
```suggestion
  if (!handle->data) goto fail;
```

Comment (Bilal2453) [reply src/stream.c:44]: I should've commited the changes myself instead of using that Github commit suggestion thing, my bad

**Review by squeek502 — APPROVED** [review]

**Comment by squeek502** [comment]
Thanks!

**Comment by Bilal2453** [comment]
No worries, thank you for helping me out with this, still learning my way.
(Also sorry for that half-failed squash attempt on my end lol)
